// src/constants/icons.ts
import {
    SiJavascript,
    SiReact,
    SiRedux,
    SiTypescript,
    SiNextdotjs,
    SiExpress,
    SiMongodb,
    SiMysql,
    SiGit,
    SiDocker,
    SiKubernetes,
    SiAntdesign,
    SiTailwindcss,
    SiMui,
    SiCss3,
    SiHtml5,
    SiSass,
    SiJest,
    SiNetlify,
    SiJira,
    SiAtlassian,
    SiPostman,
    SiVitest,
    SiFirebase,
    SiDatadog,
} from "react-icons/si";
import { TbBrandCSharp } from "react-icons/tb";
import { FaNodeJs } from "react-icons/fa";
import { DiVisualstudio } from "react-icons/di";

export const skills = [
    { name: "JavaScript", icon: SiJavascript },
    { name: "React", icon: SiReact },
    { name: "Redux", icon: SiRedux },
    { name: "TypeScript", icon: SiTypescript },
    { name: "Next.js", icon: SiNextdotjs },
    { name: "Node.js", icon: FaNodeJs },
    { name: "Express.js", icon: SiExpress },
    { name: "MongoDB", icon: SiMongodb },
    { name: "MySQL", icon: SiMysql },
    { name: "Git", icon: SiGit },
    { name: "Docker", icon: SiDocker },
    { name: "Kubernetes", icon: SiKubernetes },
    { name: "Ant Design", icon: SiAntdesign },
    { name: "Tailwind CSS", icon: SiTailwindcss },
    { name: "Material UI", icon: SiMui },
    { name: "CSS3", icon: SiCss3 },
    { name: "HTML5", icon: SiHtml5 },
    { name: "SASS", icon: SiSass },
    { name: "Jest", icon: SiJest },
    { name: "Netlify", icon: SiNetlify },
    { name: "Jira", icon: SiJira },
    { name: "Atlassian", icon: SiAtlassian },
    { name: "VS Code", icon: DiVisualstudio },
    { name: "Postman", icon: SiPostman },
    { name: "C#", icon: TbBrandCSharp },
    { name: "Vitest", icon: SiVitest },
    { name: "Firebase", icon: SiFirebase },
    { name: "Datadog", icon: SiDatadog },
];
