// src/constants/icons.ts
import {
    SiJavascript,
    SiReact,
    SiRedux,
    SiTypescript,
    SiNextdotjs,
    SiExpress,
    SiMongodb,
    SiMysql,
    SiGit,
    SiDocker,
    SiKubernetes,
    SiAntdesign,
    SiTailwindcss,
    SiMui,
    SiCss3,
    SiHtml5,
    SiSass,
    SiJest,
    SiNetlify,
    SiJira,
    SiAtlassian,
    SiPostman,
    SiVitest,
    SiFirebase,
    SiDatadog,
} from "react-icons/si";
import { TbBrandCSharp } from "react-icons/tb";
import { FaNodeJs } from "react-icons/fa";
import { DiVisualstudio } from "react-icons/di";

export const skills = [
    { id: 1, name: "JavaScript", icon: SiJavascript },
    { id: 2, name: "React", icon: SiReact },
    { id: 3, name: "Redux", icon: SiRedux },
    { id: 4, name: "TypeScript", icon: SiTypescript },
    { id: 5, name: "Next.js", icon: SiNextdotjs },
    { id: 6, name: "Node.js", icon: FaNodeJs },
    { id: 7, name: "Express.js", icon: SiExpress },
    { id: 8, name: "MongoDB", icon: SiMongodb },
    { id: 9, name: "MySQL", icon: SiMysql },
    { id: 10, name: "Git", icon: SiGit },
    { id: 11, name: "Docker", icon: SiDocker },
    { id: 12, name: "Kubernetes", icon: SiKubernetes },
    { id: 13, name: "Ant Design", icon: SiAntdesign },
    { id: 14, name: "Tailwind CSS", icon: SiTailwindcss },
    { id: 15, name: "Material UI", icon: SiMui },
    { id: 16, name: "CSS3", icon: SiCss3 },
    { id: 17, name: "HTML5", icon: SiHtml5 },
    { id: 18, name: "SASS", icon: SiSass },
    { id: 19, name: "Jest", icon: SiJest },
    { id: 20, name: "Netlify", icon: SiNetlify },
    { id: 21, name: "Jira", icon: SiJira },
    { id: 22, name: "Atlassian", icon: SiAtlassian },
    { id: 23, name: "VS Code", icon: DiVisualstudio },
    { id: 24, name: "Postman", icon: SiPostman },
    { id: 25, name: "C#", icon: TbBrandCSharp },
    { id: 26, name: "Vitest", icon: SiVitest },
    { id: 27, name: "Firebase", icon: SiFirebase },
    { id: 28, name: "Datadog", icon: SiDatadog },
];

