export const APP_COLORS = {
    MAIN_BG_COLOR: "#e3e6e6",
    PRIMARY_WHITE_COLOR: "#ffffff",
    SECONDARY_WHITE_COLOR: "#f0f0f0",
    SECONDARY_BG_COLOR: "#f5f5f5",
    PRIMARY_TEXT_COLOR: "#333333",
    SECONDARY_COLOR: "#4169E1",
    SECONDARY_TEXT_COLOR: "#555555",
    PRIMARY_GREEN_COLOR: "#93d600",
    PRIMARY_YELLOW_COLOR: "#facc15",
};

export const THEME_COLORS = {
    THEME_GREEN: "#93d600",
    THEME_YELLOW: "#facc15",
}
